### ISSUE TITLE
Can the header length be adjusted? I want it to fit my block width

### ISSUE THREAD

**Issue by liuke101** [mugiwara85/CodeblockCustomizer#9] opened 2023-04-30 15:43 UTC
I found that the header defaults to full width in edit mode.This causes the header to be much larger than the code block, which affects the aesthetics

**Comment by mugiwara85** [comment] 2023-04-30 21:31
Could you explain that a little bit more in detail? The header is exactly as long as the codeblock.

**Comment by mugiwara85** [comment] 2023-05-02 10:05
Is that the same setting as marked here? (Readable line length). If I enable it, then it works for me. Do you have any other plugins installed? If yes, try to disable them, to see if maybe there is an interference with one of them. Or did you make any other changes in CSS or something else?
![image](https://user-images.githubusercontent.com/65603765/235638328-adaf03e5-e65c-4e26-ac50-c79d1c409793.png)
![image](https://user-images.githubusercontent.com/65603765/235638473-31c4d4e7-71a1-43f6-ace7-cc3cc4ebc55d.png)

**Comment by liuke101** [comment] 2023-05-02 10:09
> 

Oh, maybe it's my personal reasons. Thanks for your reply

**Comment by mugiwara85** [comment] 2023-05-02 10:13
If you find out which plugin, or what settings causes this, I can check it, but I need to know first, what causes this behavior.

**Comment by liuke101** [comment] 2023-05-03 05:47
> If you find out which plugin, or what settings causes this, I can check it, but I need to know first, what causes this behavior.

I have tested several of the most popular themes in the new warehouse and found that only minimal theme exists in the above condition. I think there may be a conflict between the plug-in and minimal theme, I hope you can check it.

**Comment by mugiwara85** [comment] 2023-05-03 07:37
I can confirm this behavior with minimal theme. I will look at it, what is causing this.

**Comment by mugiwara85** [comment] 2023-05-04 20:08
It is fixed in version 1.1.7

**Closed** 2023-05-05 13:51 UTC
